---
title: "Nicola S-R"
author: "Colin Bailey"
date: "2025-04-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyverse)
library(rstan)
library(rstanarm)
library(shinystan)
library(bayesplot)
library(pkgbuild)
library(boot)
library(loo)
library(MASS)
#install.packages("remotes")    #run this line and the next once to get access to the sgen solver that DFO has developed
#remotes::install_github("Pacific-salmon-assess/samSim")  
library(samSim) #package that DFO created with the sgen solver to estimate sgen given stock recruit parameters

pkgbuild::has_build_tools(debug = TRUE)

rstan_options(auto_write=T)

options(mc.cores = parallel::detectCores())

nic_dat <- read.csv("SP_1.2//Data_in//nic_dat.csv")
head(nic_dat)
```


```{r data vis}

nic_dat %>% ggplot(aes(x = total_spawners, y = no_recruits))+
  geom_point()+
  theme_classic()

```

Note that hatchery spawners are baked into the SR analysis... Hatchery spawners included with total spawners, but not included in the recruits for the model. This means that we are not considering the differential productivity between hatchery and NO spawners in these analyses.

```{r ricker model}

#creating the list of data to feed to Stan
dat <- list("N" = nrow(nic_dat),                  #number of years of data
            "surv" = (logit(nic_dat$smolt_age3_survival) - mean(logit(nic_dat$smolt_age3_survival))) / sd(logit(nic_dat$smolt_age3_survival)), #logit-transformed smolt to age 3 adult survival
            "lrs" = pull(nic_dat %>% mutate(lrs = log(no_recruits/total_spawners)) %>% dplyr::select(lrs)),  #log natural origin recruits per spawner (HO & NO)
            "S" = nic_dat$total_spawners, #vector of total spawner abundance
            "mlogit_surv" = 0) #mean logit-transformed survival

#running the Stan model
fit <- stan(file = "SP_1.2/Scripts/Ricker.stan", data = dat, chains=6,
                    iter=10000, cores=6, thin = 1,
                    control=list("max_treedepth"=15,"adapt_delta"=0.8),
                    pars=c("beta", "alpha", "gamma", "sigma", "Smax", "rho", "surv_est", "nu_Y", "nu_rec", "srep", "smsy_85", "smsy", "umsy", "alpha_prime", "srep_prime"))

#fit summary
out <- summary(fit)
saveRDS(fit, "SP_1.2//Results/fit.rds")
saveRDS(out, "SP_1.2//Results/out.rds")

fit <- readRDS("SP_1.2//Results/fit.rds")
out <- readRDS("SP_1.2//Results/out.rds")

```


```{r results vis}

#mean prediction functions for Ricker with SAS index covariate
ricker <- function(x){
  (-out$summary[1,1] * x + out$summary[2,1])
}

ricker_exp <- function(x){
  exp(-out$summary[1,1] * x + out$summary[2,1]) * x
}

#drawing from the posterior distribution to show error in relationships
alpha <- as.vector(extract(fit)[2])
beta <- as.vector(extract(fit)[1])
gamma <- as.data.frame(extract(fit)[3])
post <- data.frame(alpha, beta, gamma) %>% mutate(beta = beta * -1)

qpost <- post %>% filter(alpha > quantile(post$alpha, probs = c(0.025)) & alpha < quantile(post$alpha, probs = c(0.975)))

set.seed(42)
poste <- sample_n(qpost, 1000)

#showing a sample of 1000 alternative lines within the posterior
uncertainty_ricker <- apply(as.matrix(poste), 1, function(poste) {
  stat_function(fun=function(x){(poste[1] + poste[2] * x)}, colour="blue",
                alpha = 0.02, linewidth = 0.01)
  })

uncertainty_ricker_exp <- apply(as.matrix(poste), 1, function(poste) {
  stat_function(fun=function(x){exp(poste[1] + poste[2] * x) * x}, colour="blue",
                alpha = 0.02, linewidth = 0.01)
  })

#S-R plot for relationship with SAS index covariate
nic_dat %>% ggplot(aes(x = total_spawners, y = log(no_recruits/total_spawners)))+
  geom_point()+
  uncertainty_ricker+
  geom_function(fun = ricker)+
  labs(x = "Spawners(n)", y = "log(Recruits/Spawner)")+
  theme_classic()

nic_dat %>% ggplot(aes(x = total_spawners, y = no_recruits))+
  geom_point()+
  geom_function(fun = ricker_exp)+
  geom_abline(aes(slope = 1, intercept = 0), colour = "black", linetype = "dashed")+
  uncertainty_ricker_exp+
  labs(x = "Spawners(n)", y = "Recruits(n)")+
  scale_y_continuous(limits = c(0, 30000))+
  theme_classic()


#Diagnostic Plots

##Pairs Plots
pairs(fit, pars = c("beta", "alpha", "gamma", "sigma", "surv_est", "rho"))

##Predicted vs observed
nic_dat$pred <- out$summary[8:36,1]

###predicted ~ observed
nic_dat %>% ggplot(aes(x = log(no_recruits/total_spawners), y = pred))+
  geom_point()+
  geom_abline(aes(slope = 1, intercept = 0), colour = "black", linetype = "dashed")+
  labs(x = "Observed", y = "Predicted")+
  theme_classic()

###observed - predicted ~ brood year
nic_dat %>% ggplot(aes(x = brood_year, y = log(no_recruits/total_spawners) - pred))+
  geom_point()+
  geom_abline(aes(slope = 0, intercept = 0), colour = "black", linetype = "dashed")+
  labs(x = "Brood Year", y = "Observed - Predicted")+
  theme_classic()


#creating a list of dataframes of parameter vectors to feed to the sgen solver -> note that negative values of sMSY are not sensible, thus all negative values from the posterior are converted to 0
theta = data.frame(alpha = as.vector(alpha), beta = as.vector(beta), sigma = as.vector(extract(fit)[4]))
sMSY = ifelse(unlist(data.frame(as.vector(extract(fit)[12]))) > 0, unlist(data.frame(as.vector(extract(fit)[12]))), 0)

#calculating sgen for each iteration of both models
sgen <- matrix(nrow = nrow(theta), ncol = 1)
for(i in 1:nrow(theta)){
  sgen[i] <- sGenSolver(unlist(theta[i,]), sMSY[i])
  }

quantile(unlist(sgen), probs = c(0.025, 0.5, 0.975))
quantile(sMSY, probs = c(0.025, 0.5, 0.975))

sGenDirect <- function(loga, b){
 sMSY <- ( 1 - gsl::lambert_W0 (exp ( 1 - loga) ) ) / b
 a <- exp(loga)
 -1/b*gsl::lambert_W0(-b*sMSY/a)
}

sgen <- matrix(nrow = nrow(theta), ncol = 1)
for(i in 1:nrow(theta)){
  sgen[i] <- sGenDirect(unlist(theta[i,1]), unlist(theta[i,2]))
}

#95% CI and median sgen value for Nicola River
quantile(unlist(sgen), probs = c(0.025, 0.5, 0.975))

```


```{r extract posterior data for samsim}

#drawing from the posterior distribution to show error in relationships
alpha <- as.vector(extract(fit)[2])
beta <- as.vector(extract(fit)[1])
sigma <- as.data.frame(extract(fit)[4])
alpha_prime <- as.data.frame(extract(fit)[14])
post <- data.frame(alpha, beta, sigma, alpha_prime)

poste <- post[sample(nrow(post), 1000),]

saveRDS(poste, "data\\post.rds")

```


```{r alternative Ricker models}
nic_dat <- nic_dat %>% filter(brood_year > 1992)

#creating the list of data to feed to Stan
dat <- list("N" = nrow(nic_dat),                  #number of years of data
            "surv" = (logit(nic_dat$smolt_age3_survival) - mean(logit(nic_dat$smolt_age3_survival))) / sd(logit(nic_dat$smolt_age3_survival)), #logit-transformed smolt to age 3 adult survival
            "lrs" = pull(nic_dat %>% mutate(lrs = log(no_recruits/total_spawners)) %>% dplyr::select(lrs)),  #log natural origin recruits per spawner (HO & NO)
            "S" = nic_dat$total_spawners, #vector of total spawner abundance
            "mlogit_surv" = 0) #mean logit-transformed survival

#running the Stan model
fit <- stan(file = "Scripts/Ricker_sans1992.stan", data = dat, chains=6,
                    iter=10000, cores=6, thin = 1,
                    control=list("max_treedepth"=15,"adapt_delta"=0.8),
                    pars=c("beta", "alpha", "gamma", "sigma", "nu_Y", "mu_gamma_Y", "nu_rec", "srep", "smsy_85", "smsy", "umsy"))

#fit summary
out92 <- summary(fit)
saveRDS(out, "Results/out.rds")

#running the Stan model with RW
fit_rw <- stan(file = "Scripts/Ricker_rw.stan", data = dat, chains=6,
                    iter=10000, cores=6, thin = 1,
                    control=list("max_treedepth"=15,"adapt_delta"=0.8),
                    pars=c("beta", "alpha", "sigma", "nu_Y", "nu_rec", "srep", "smsy_85", "smsy", "umsy"))

#fit summary
out_rw <- summary(fit_rw)
saveRDS(out_rw, "Results/out_rw.rds")


```


```{r random walk model vis}

#mean prediction functions for Ricker with random walk autocorrelation and no SAS index parameter
ricker_rw <- function(x){
  (out_rw$summary[1,1] * x + out_rw$summary[2,1])
}

ricker_exp_rw <- function(x){
  exp(out_rw$summary[1,1] * x + out_rw$summary[2,1]) * x
}

#drawing from the posterior distribution to show error in relationships
alpha <- as.vector(extract(fit_rw)[2])
beta <- as.vector(extract(fit_rw)[1])
post <- data.frame(alpha, beta)

set.seed(42)
poste <- sample_n(post, 1000)

#showing a sample of 1000 alternative lines within the posterior
uncertainty_ricker <- apply(as.matrix(poste), 1, function(poste) {
  stat_function(fun=function(x){(poste[1] + poste[2] * x)}, colour="red",
                alpha = 0.02, linewidth = 0.01)
  })

uncertainty_ricker_exp <- apply(as.matrix(poste), 1, function(poste) {
  stat_function(fun=function(x){exp(poste[1] + poste[2] * x) * x}, colour="red",
                alpha = 0.02, linewidth = 0.01)
  })

nic_dat %>% ggplot(aes(x = total_spawners, y = log(no_recruits/total_spawners)))+
  geom_point()+
  uncertainty_ricker+
  geom_function(fun = ricker_rw)+
  theme_classic()

nic_dat %>% ggplot(aes(x = total_spawners, y = no_recruits))+
  geom_point()+
  geom_abline(aes(slope = 1, intercept = 0))+
  uncertainty_ricker_exp+
  geom_function(fun = ricker_exp_rw)+
  theme_classic()

```

