---
title: "Simulation - post processing"
author: "C. Bailey"
date: "5/29/2025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, read in scenario outputs}

simPar <- read.csv("data\\samsim pars\\SimPars.csv")
CUPar <- read.csv("data\\samsim pars\\CUPars.csv")

quants <- c(0.15, 0.25, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.75, 0.85)

srdat_aq <- list()

for(k in 1:length(quants)){
   hcrDatalist<-list()
   srData<- list()
   for(a in seq_len(nrow(simPar))){
      hcrDatalist[[a]] <- readRDS(paste("./outputs",quants[k],"/SamSimOutputs/simData/",
                                         simPar$nameOM[a],"/", 
                                         simPar$scenario[a],"/",
                                         paste(simPar$nameOM[a],"_", simPar$nameMP[a], "_",
                                               "CU_HCR_PM.RData",sep=""), sep=""))$hcrDatout
      hcrDatalist[[a]]$scenario<-simPar$scenario[a]
      hcrDatalist[[a]]$nameOM<-simPar$nameOM[a]
      hcrDatalist[[a]]$nameMP<-simPar$nameMP[a]
      
      srData[[a]] <- readRDS(paste("./outputs",quants[k],"/SamSimOutputs/simData/", 
                         simPar$nameOM[a],"/",
                         simPar$scenario[a],"/",
                         paste(simPar$nameOM[a],"_", simPar$nameMP[a], "_", "CUsrDat.RData",sep=""), sep=""))$srDatout
      srData[[a]]$scenario<-simPar$scenario[a]
      srData[[a]]$nameOM<-simPar$nameOM[a]
      srData[[a]]$nameMP<-simPar$nameMP[a]
      }
   hcrdat <- do.call(rbind,hcrDatalist)
   srdat<- do.call(rbind,srData)
   hcrdat<-hcrdat[hcrdat$year>50,] #remove burn-in period
   srdat<-srdat[srdat$year>50,]
   
   #hcrdat maybe not needed - has catch statistics though
   hcrdat=hcrdat[order(hcrdat$scenario,hcrdat$iteration,hcrdat$CU,hcrdat$year),]
   srdat=srdat[order(srdat$scenario,srdat$iteration,srdat$CU,srdat$year),]
   
   srdat_aq[[k]] <- srdat
}



```
