---
title: "SP_1.2_SIM"
author: "Colin Bailey"
date: "2025-04-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyverse)
library(rstan)
library(rstanarm)
library(shinystan)
library(bayesplot)
library(pkgbuild)
library(boot)
library(loo)
library(MASS)
#install.packages("remotes")    #run this line and the next once to get access to the sgen solver that DFO has developed
#remotes::install_github("Pacific-salmon-assess/samSim", ref="sbccnk", force=TRUE)
library(samSim) #package that DFO created with the sgen solver to estimate sgen given stock recruit parameters

pkgbuild::has_build_tools(debug = TRUE)

rstan_options(auto_write=T)

options(mc.cores = parallel::detectCores())

#escapement data
esc_dat <- read.csv("SP_1.2\\Data_in\\sp1.2_smu_no_escape.csv")
head(esc_dat)

#posterior data
pos_dat <- readRDS("data\\post.rds")
head(pos_dat)

#age data
age_dat <- read.csv("SP_1.2\\Data_in\\rec_age_comp.csv")
head(age_dat)

```


```{r sim data prep}

#Escapement correlation - filter out pops with high hatchery influence & no NO estimates, and filter out years with NAs
`%!in%` <- Negate(`%in%`)
dat <- esc_dat %>% filter(Pop_Name %!in% c("NICOLA RIVER-UPPER", "SPIUS CREEK", "COLDWATER RIVER"))

source("R\\pop_cor.R")

corr <- pop_cor(dat)
corr

#Ricker Parameter Posteriors - fill in the beta column based on the alpha and sigma posterior from the Nicola S-R
post <- readRDS("data\\post.rds")

rws <- sample(x = 1:30000, size = 1000, replace = F)

post_nic <- post[rws,] %>% arrange(beta)



#Tau for age variance and mean proportions at age (3,4,5)
ppnMat <- age_dat %>% mutate(p3 = a3/(a3 + a4 + a5),
                   p4 = a4/(a3 + a4 + a5),
                   p5 = a5/(a3 + a4 + a5)) %>% dplyr::select(p3, p4, p5)

source("R\\age_tau.R")

tau <- tau_comp(ppnMat)$tau
m_props <- tau_comp(ppnMat)$pa

```


```{r sim input files}






```

