---
title: "5 YR Window S-R Parameter Estimation"
author: "Colin Bailey"
date: "2025-10-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyverse)
library(rstan)
library(rstanarm)
library(shinystan)
library(bayesplot)
library(pkgbuild)
library(boot)
library(loo)
library(MASS)
library(dglm)

pkgbuild::has_build_tools(debug = TRUE)
rstan_options(auto_write=T)
options(mc.cores = parallel::detectCores())

#read in and check data
nic_dat <- read.csv("SP_1.2//Data_in//nic_dat.csv")
head(nic_dat)

```

Plot with posterior for each black point (plot combo'd posterior as violin plot), still plot the black points too, keep the red point and CI the same.
```{r ricker model}

# wind_out <- list()
# beta_out <- list()
# alpha_out <- list()
# sigma_out <- list()
# Smax_out <- list()
# smsy_85_out <- list()
# umsy_out <- list()
# 
# for(i in 1:(nrow(nic_dat) - 4)){
#   nico_dat <- nic_dat[(i):(i+4),]
# 
#   #creating the list of data to feed to Stan
#   dat <- list("N" = nrow(nico_dat),                  #number of years of data
#             "surv" = (logit(nico_dat$smolt_age3_survival) - mean(logit(nico_dat$smolt_age3_survival))) /
#               sd(logit(nico_dat$smolt_age3_survival)), #logit-transformed smolt to age 3 adult survival
#             "lrs" = pull(nico_dat %>% mutate(lrs = log(no_recruits/total_spawners)) %>% dplyr::select(lrs)),  #log natural origin  recruits per spawner (HO & NO)
#             "S" = nico_dat$total_spawners, #vector of total spawner abundance
#             "mlogit_surv" = 0) #mean logit-transformed survival
# 
#   #running the Stan model
#   fit <- stan(file = "SP_1.2/Scripts/Ricker.stan", data = dat, chains=6,
#                     iter=10000, cores=6, thin = 1,
#                     control=list("max_treedepth"=15,"adapt_delta"=0.8),
#                     pars=c("beta", "alpha", "sigma", "Smax", "smsy_85", "umsy"))
#   #fit summary
#   wind_out[i] <- summary(fit)
#   beta_out[i] <- as.vector(extract(fit)[1])
#   alpha_out[i] <- as.vector(extract(fit)[2])
#   sigma_out[i] <- as.vector(extract(fit)[3])
#   Smax_out[i] <- as.vector(extract(fit)[4])
#   smsy_85_out[i] <- as.vector(extract(fit)[5])
#   umsy_out[i] <- as.vector(extract(fit)[6])
# }
# 
# saveRDS(wind_out, "wind_out.RDS")
# saveRDS(beta_out, "beta_out.RDS")
# saveRDS(alpha_out, "alpha_out.RDS")
# saveRDS(sigma_out, "sigma_out.RDS")
# saveRDS(Smax_out, "Smax_out.RDS")
# saveRDS(smsy_85_out, "smsy_85_out.RDS")
# saveRDS(umsy_out, "umsy_out.RDS")

out <- readRDS("wind_out.RDS")
b_out <- data.frame(b = sample(unlist(readRDS("beta_out.RDS")), 2500), x = rep(0, 2500))
a_out <- data.frame(b = sample(unlist(readRDS("alpha_out.RDS")), 2500), x = rep(0, 2500))
s_out <- data.frame(b = sample(unlist(readRDS("sigma_out.RDS")), 2500), x = rep(0, 2500))
sx_out <- data.frame(b = sample(unlist(readRDS("Smax_out.RDS")) * 0.2, 2500), x = rep(0, 2500))
sy_out <- data.frame(b = sample(unlist(readRDS("smsy_85_out.RDS")), 2500), x = rep(0, 2500))
u_out <- data.frame(b = sample(unlist(readRDS("umsy_out.RDS")), 2500), x = rep(0, 2500))

beta <- rep(99, (nrow(nic_dat) - 4))
alpha <- rep(99, (nrow(nic_dat) - 4))
sigma <- rep(99, (nrow(nic_dat) - 4))
Smax_20 <- rep(99, (nrow(nic_dat) - 4))
smsy_85 <- rep(99, (nrow(nic_dat) - 4))
umsy <- rep(99, (nrow(nic_dat) - 4))

for(i in 1:(nrow(nic_dat) - 4)){
  beta[i] <- out[[i]][1,1]
  alpha[i] <- out[[i]][2,1]
  sigma[i] <- out[[i]][3,1]
  Smax_20[i] <- out[[i]][4,1] * 0.2
  smsy_85[i] <- out[[i]][5,1]
  umsy[i] <- out[[i]][6,1]
}

#window runs
runs <- data.frame(beta, alpha, sigma, Smax_20, smsy_85, umsy) %>% 
  pivot_longer(cols = 1:6)
#full timeseries outputs
full_out <- as.data.frame(readRDS("SP_1.2//Results/out.rds")$summary)[c(1,2,4,5,67,69), c(1,4,5,7,8)]

#beta
ggplot(data = b_out, aes(y = b, x = x))+
  geom_violin(data = b_out, colour = "grey", fill = "grey")+ 
  geom_jitter(data = b_out, aes(y = b, x = x), width = 0.05, height = 0, size = 0.2, alpha = 0.2)+
  geom_jitter(data = runs %>% filter(name == "beta"), aes(y = value, x = 0), width = 0.05, height = 0, size = 1.5)+
  geom_point(aes(y = full_out[1,1], x = 0), colour = "red", size = 3)+
  geom_errorbar(aes(ymin = full_out[1,3], ymax = full_out[1,4]), width = 0.1, colour = "red")+
  labs(x = "", y = "Beta")+
  theme_classic()

#alpha
ggplot(data = a_out, aes(y = b, x = x))+
  geom_violin(data = a_out, colour = "grey", fill = "grey")+ 
  geom_jitter(data = a_out, aes(y = b, x = x), width = 0.05, height = 0, size = 0.2, alpha = 0.2)+
  geom_jitter(data = runs %>% filter(name == "alpha"), aes(y = value, x = 0), width = 0.05, height = 0, size = 1.5)+
  geom_point(aes(y = full_out[2,1], x = 0), colour = "red", size = 3)+
  geom_errorbar(aes(ymin = full_out[2,3], ymax = full_out[2,4]), width = 0.1, colour = "red")+
  labs(x = "", y = "Alpha")+
  theme_classic()

#sigma
ggplot(data = s_out, aes(y = b, x = x))+
  geom_violin(data = s_out, colour = "grey", fill = "grey")+ 
  geom_jitter(data = s_out, aes(y = b, x = x), width = 0.05, height = 0, size = 0.2, alpha = 0.2)+
  geom_jitter(data = runs %>% filter(name == "sigma"), aes(y = value, x = 0), width = 0.05, height = 0, size = 1.5)+
  geom_point(aes(y = full_out[3,1], x = 0), colour = "red", size = 3)+
  geom_errorbar(aes(ymin = full_out[3,3], ymax = full_out[3,4]), width = 0.1, colour = "red")+
  labs(x = "", y = "Sigma")+
  theme_classic()

#Smax_20
ggplot(data = sx_out, aes(y = b, x = x))+
  geom_violin(data = sx_out, colour = "grey", fill = "grey")+ 
  geom_jitter(data = sx_out, aes(y = b, x = x), width = 0.05, height = 0, size = 0.2, alpha = 0.2)+
  geom_jitter(data = runs %>% filter(name == "Smax_20"), aes(y = value, x = 0), width = 0.05, height = 0, size = 1.5)+
  geom_point(aes(y = full_out[4,1] * 0.2, x = 0), colour = "red", size = 3)+
  geom_errorbar(aes(ymin = full_out[4,3] * 0.2, ymax = full_out[4,4] * 0.2), width = 0.1, colour = "red")+
  labs(x = "", y = "Smax_20")+
  theme_classic()

#smsy_85
ggplot(data = sy_out, aes(y = b, x = x))+
  geom_violin(data = sy_out, colour = "grey", fill = "grey")+ 
  geom_jitter(data = sy_out, aes(y = b, x = x), width = 0.05, height = 0, size = 0.2, alpha = 0.2)+
  geom_jitter(data = runs %>% filter(name == "smsy_85"), aes(y = value, x = 0), width = 0.05, height = 0, size = 1.5)+
  geom_point(aes(y = full_out[5,1], x = 0), colour = "red", size = 3)+
  geom_errorbar(aes(ymin = full_out[5,3], ymax = full_out[5,4]), width = 0.1, colour = "red")+
  labs(x = "", y = "SMSY 85")+
  theme_classic()

#umsy
ggplot(data = u_out, aes(y = b, x = x))+
  geom_violin(data = u_out, colour = "grey", fill = "grey")+ 
  geom_jitter(data = u_out, aes(y = b, x = x), width = 0.05, height = 0, size = 0.2, alpha = 0.2)+
  geom_jitter(data = runs %>% filter(name == "umsy"), aes(y = value, x = 0), width = 0.05, height = 0, size = 1.5)+
  geom_point(aes(y = full_out[6,1], x = 0), colour = "red", size = 3)+
  geom_errorbar(aes(ymin = full_out[6,3], ymax = full_out[6,4]), width = 0.1, colour = "red")+
  labs(x = "", y = "UMSY")+
  theme_classic()

```
